server:
  port: 8000

spring:
  application:
    name: APIGateWay
  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

info:
  name: API Gateway

logging:
  file: logfile/gw.log


zuul:
  routes:
    front:
      path: /front/**
      serviceId: FrontendService
    contents:
      path: /contents/**
      serviceId: ContentsService